### ISSUE TITLE
Failed to load the atom-alignment package

### ISSUE THREAD

**Issue by coolicer** [Freyskeyd/atom-alignment#38]
[Enter steps to reproduce below:]
1. install atom-alignment
2. restart app

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-alignment](https://github.com/Freyskeyd/atom-alignment) package, v0.12.1
### Stack Trace

Failed to load the atom-alignment package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/mac/.atom/packages/atom-alignment/lib/aligner.coffee:7:7)
    at Object.<anonymous> (/Users/mac/.atom/packages/atom-alignment/lib/aligner.coffee:323:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
seti-ui, v0.7.1
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by Freyskeyd** [comment]
Can't reproduce.

Reopen if needed.
