### ISSUE TITLE
Uncaught TypeError: Cannot read property 'detach' of undefined

### ISSUE THREAD

**Issue by monlone** [Freyskeyd/atom-alignment#51]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [atom-alignment](https://github.com/Freyskeyd/atom-alignment) package, v0.12.1

### Stack Trace

Uncaught TypeError: Cannot read property 'detach' of undefined

```
At /C:/Users/shaohua/.atom/packages/php-class-tree/lib/php-class-tree.coffee:44

TypeError: Cannot read property 'detach' of undefined
    at PhpClassTree.detach (file:///C:/Users/shaohua/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
    at Function.Main.getPhpClassTreeByEditor (file:///C:/Users/shaohua/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
    at file:///C:/Users/shaohua/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
    at Emitter.module.exports.Emitter.emit (D:\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at D:\Atom\resources\app.asar\src\pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (D:\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (D:\Atom\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (D:\Atom\resources\app.asar\src\pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (D:\Atom\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.19
autocomplete-php, v0.3.7
color-picker, v2.0.14
docblockr, v0.7.3
emmet, v2.3.17
jsformat, v0.9.0
language-blade, v0.16.0
laravel, v0.7.0
laravel-snippets, v2.1.0
minimap, v4.18.2
php-cs-fixer, v2.5.1
php-debug, v0.1.4
pigments, v0.19.3
symbols-tree-view, v0.10.1
travis-ci-status, v0.18.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by unoframille** [comment]
TypeError: Cannot read property 'detach' of undefined
    at PhpClassTree.detach (/Users/francescomosca/.atom/packages/php-class-tree/lib/php-class-tree.coffee:34:14)
    at Function.Main.getPhpClassTreeByEditor (/Users/francescomosca/.atom/packages/php-class-tree/lib/php-class-tree.coffee:245:17)
    at /Users/francescomosca/.atom/packages/php-class-tree/lib/php-class-tree.coffee:212:22
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:493:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:16:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:280:26)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:318:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:471:27)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
